### ISSUE TITLE
Fails to build with Meson 0.61.0

### ISSUE THREAD

**Issue by jbeich** [p11-glue/p11-kit#406] opened 2022-01-12 01:00 UTC
Regressed by https://github.com/mesonbuild/meson/commit/566c2c9a9c98

```
$ meson setup -Dgtk_doc=true _build
[...]
doc/manual/meson.build:72:8: ERROR: gnome.gtkdoc keyword argument 'dependencies' was of type array[CustomTarget | PkgConfigDependency] but should have been array[Dependency | SharedLibrary | StaticLibrary]
```
 https://github.com/p11-glue/p11-kit/blob/04f85857b3029fd28c7c731aef89f61b22e846d3/doc/manual/meson.build#L1-L22
https://github.com/p11-glue/p11-kit/blob/04f85857b3029fd28c7c731aef89f61b22e846d3/doc/manual/meson.build#L76

**Comment by eli-schwartz** [comment] 2022-01-12 05:08
Fixed by #407, this is not a meson regression. xml_deps did not do anything, because that kwarg was not supposed to accept them.

**Closed** 2022-01-12 10:18 UTC
